
server:
  port: 5004

taskService:
  url: http://loclhost:5003//api/tasks

loginService:
  url: http://localhost:5001/web/v1


spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      time-to-live: 60000
      connect-timeout: 50000

  cache:
    type: redis
    cache-names: SubmissionService
    redis:
      time-to-live: 60000

  application:
    name: SUBMISSION_SERVICE

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Task_Management
    username: postgres
    password: 5468

  jpa:
    hibernate:
      ddl-auto: create

    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true


management:
  endpoints:
    web:
      base-path: /monitor
      exposure:
        include: beans,health,info,mapping,appDetail

  endpoint:
    health:
      show-details: always
      show-components: always

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8070/eureka/